android {
    ...
    signingConfigs {
        release {
            storeFile file("my-release-key.keystore")
            storePassword "android"
            keyAlias "my-key-alias"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
